"""IntellCluster data application entrypoint.

The original data app and response polish live in ``main_data_core``. This thin
layer mounts discovery-focused directory routes and structured metadata without
coupling SEO work to ingestion or the core directory UI.
"""

from main_data_core import app
from intelligence.company_directory import router as company_directory_router
from intelligence.compliance_export import router as compliance_export_router
from intelligence.evidence_sitemap import install_evidence_sitemaps
from intelligence.profile_guard import install_profile_guard
from intelligence.search_empty_state import install_search_empty_state
from intelligence.search_signal_ui import install_search_signal_ui
from intelligence.sec_api import router as sec_api_router
from intelligence.sec_export import router as sec_export_router
from intelligence.sec_profile_ui import install_sec_profile_ui
from intelligence.seo import install_seo_middleware, router as seo_router
from intelligence.sitemap_cache import install_sitemap_cache

app.include_router(company_directory_router)
app.include_router(compliance_export_router)
app.include_router(sec_api_router)
app.include_router(sec_export_router)
app.include_router(seo_router)
install_profile_guard(app)
install_sec_profile_ui(app)
install_search_empty_state(app)
install_search_signal_ui(app)
install_seo_middleware(app)
install_evidence_sitemaps(app)
# Install the cache last so it is the outermost sitemap middleware and can cache
# evidence-tier sitemap responses generated by the layers above.
install_sitemap_cache(app)
