"""IntellCluster data application entrypoint.

The original data app and response polish live in ``main_data_core``. This thin
layer mounts discovery-focused directory routes and structured metadata without
coupling SEO work to ingestion or the core directory UI.
"""

from main_data_core import app
from intelligence.company_directory import router as company_directory_router
from intelligence.company_routes import router as company_page_router
from intelligence.compliance_export import router as compliance_export_router
from intelligence.evidence_sitemap import install_evidence_sitemaps
from intelligence.importyeti_api import router as importyeti_api_router
from intelligence.post_ingest_readiness import router as post_ingest_readiness_router
from intelligence.route_hardening import prune_shadowed_legacy_routes
from intelligence.search_empty_state import install_search_empty_state
from intelligence.search_signal_ui import install_search_signal_ui
from intelligence.sec_api import router as sec_api_router
from intelligence.sec_export import router as sec_export_router
from intelligence.sec_profile_ui import install_sec_profile_ui
from intelligence.seo import install_seo_middleware, router as seo_router
from intelligence.sitemap_cache import install_sitemap_cache
from intelligence.sync_observability import router as sync_observability_router

# ``main_data_core`` still imports the historical UI router for pages not yet
# migrated. Remove only exact superseded routes before mounting focused modules.
prune_shadowed_legacy_routes(app)

app.include_router(company_page_router)
app.include_router(company_directory_router)
app.include_router(compliance_export_router)
app.include_router(importyeti_api_router)
app.include_router(sec_api_router)
app.include_router(sec_export_router)
app.include_router(sync_observability_router)
app.include_router(post_ingest_readiness_router)
app.include_router(seo_router)
install_sec_profile_ui(app)
install_search_empty_state(app)
install_search_signal_ui(app)
install_seo_middleware(app)
install_evidence_sitemaps(app)
# Install the cache last so it is the outermost sitemap middleware and can cache
# evidence-tier sitemap responses generated by the layers above.
install_sitemap_cache(app)